feat: allow clients to request info actively

diff --git a/image/app/bin/tvheadend-status b/image/app/bin/tvheadend-status
--- a/image/app/bin/tvheadend-status
+++ b/image/app/bin/tvheadend-status
@@ -1,5 +1,13 @@
 #!/bin/sh
 
+
+###############################################################################
+# Return codes
+###############################################################################
+rc_ok=0
+rc_missing_arg=1
+
+
 ###############################################################################
 # Utility functions
 ###############################################################################
@@ -10,39 +18,25 @@ log() {
   done
 }
 
-cancel() {
-  log "$*"
-  exit 1
-}
-
 require_var() {
   name="$1"
   value=$(eval "echo \"\$$name\"")
-  [ -z "$value" ] && cancel "Missing environment variable: $1"
+  [ -z "$value" ] && log "Missing environment variable: $1" && return "$rc_missing_arg"
+  return "$rc_ok"
 }
 
-require_cmd() {
-  result=$(type -t "$2")
-  if [ "$?" -eq 0 ]; then
-    case "$1" in
-    'function')
-      echo "$result" | grep -q "^$2\( is a shell function\)\?\$" && return 0
-      ;;
-    'file')
-      echo "$result" | grep -q "^.\+$2\$" && return 0
-      ;;
-    *)
-      cancel "Unsupported command: $1"
-      ;;
-    esac
-  fi
-  cancel "Error: $1 '$2' is missing."
+require_command() {
+  $(type -t "$1" | grep -q "^.\+$1\$")
+  rc="$?"
+  [ "$rc" -ne 0 ] && log "Error: command '$1' is missing."
+  return "$rc"
 }
 
 prepare_env() {
-  require_var TVHEADEND_USER
-  require_var TVHEADEND_PASSWORD
-  require_var TVHEADEND_HOST
+  require_var TVHEADEND_USER     || return "$?"
+  require_var TVHEADEND_PASSWORD || return "$?"
+  require_var TVHEADEND_HOST     || return "$?"
+
   TVHEADEND_HTTP_PORT="${TVHEADEND_HTTP_PORT:-9981}"
   TVHEADEND_HTTP_URL="${TVHEADEND_HTTP_URL:-http://$TVHEADEND_HOST:$TVHEADEND_HTTP_PORT}"
   TVHEADEND_HTTP_TIMEOUT="${TVHEADEND_HTTP_TIMEOUT:-15}"
@@ -57,10 +51,12 @@ prepare_env() {
 }
 
 print_json() {
+  require_command jq || return "$?"
   echo "$1" | jq
 }
 
 entries_to_text() {
+  require_command jq || return "$?"
   echo "$1" | jq -r ".entries[] | (.start_real | strflocaltime(\"%Y-%m-%dT%H:%M:%SZ\")) + \" \" + .channelname + \" - \" + .disp_title + if (.disp_subtitle | length > 0) then \" (\" + .disp_subtitle + \")\" else \"\" end"
 }
 
@@ -71,9 +67,10 @@ entries_to_text() {
 
 request() {
   curl $curl_options $*
-  case "$?" in
+  rc="$?"
+  case "$rc" in
   0)
-    return 0
+    return "$rc"
     ;;
   7)
     message="Failed to connect to host"
@@ -82,29 +79,10 @@ request() {
     message="Timeout after $TVHEADEND_HTTP_TIMEOUT seconds"
     ;;
   *)
-    message="cURL returned $?"
+    message="cURL returned $rc"
     ;;
   esac
-  cancel "Error: $message while trying to access $*"
-}
-
-
-###############################################################################
-# Publish via MQTT
-###############################################################################
-
-publish() {
-  require_var MQTT_BROKER_HOSTNAME
-  require_cmd file mosquitto_pub
-  command="$1"
-  topic="$2"
-  require_cmd function "$command"
-  [ -z "$topic" ] && cancel "Missing argument for MQTT topic"
-
-  message=$("$command")
-  log "Message: $message"
-
-  mosquitto_pub -h "$MQTT_BROKER_HOSTNAME" -t "$topic" -m "$message"
+  log "Error: $message while trying to access $*" && return "$rc"
 }
 
 
@@ -113,16 +91,18 @@ publish() {
 ###############################################################################
 
 get_status() {
-  subscriptions=$(get_subscriptions)
+  subscriptions=$(get_subscriptions) || return "$?"
+  require_command jq || return "$?"
   subscription_count=$(echo "$subscriptions" | jq -r ".totalCount")
-  upcoming=$(get_upcoming 1)
+  upcoming=$(get_upcoming 1) || return "$?"
   status=$(echo "$upcoming" | jq ".entries[0] | {next: [((.start_real-now) / 60)|floor, 0] | max, title: .disp_title, subtitle: .disp_subtitle, channel: .channelname, status: .sched_status, subscriptions: $subscription_count}")
 
   print_json "$status"
 }
 
 get_subscriptions() {
-  subscriptions=$(request "$TVHEADEND_HTTP_URL/api/status/subscriptions")
+  subscriptions=$(request "$TVHEADEND_HTTP_URL/api/status/subscriptions") || return "$?"
+  require_command jq || return "$?"
   subscription_titles=$(echo "$subscriptions" | jq -r ".entries[] | .title")
 
   log "Subscriptions: ${subscription_titles:-none}"
@@ -130,7 +110,8 @@ get_subscriptions() {
 }
 
 get_connections() {
-  connections=$(request "$TVHEADEND_HTTP_URL/api/status/connections")
+  connections=$(request "$TVHEADEND_HTTP_URL/api/status/connections") || return "$?"
+  require_command jq || return "$?"
   connection_peers=$(echo "$connections" | jq ".entries[] | .peer")
 
   log "Clients: $connection_peers"
@@ -143,7 +124,7 @@ get_upcoming() {
   curl_local_options="$curl_local_options --data sort=start_real"
   curl_local_options="$curl_local_options --data dir=ASC"
   curl_local_options="$curl_local_options --data limit=$limit"
-  upcoming=$(request $curl_local_options "$TVHEADEND_HTTP_URL/api/dvr/entry/grid_upcoming")
+  upcoming=$(request $curl_local_options "$TVHEADEND_HTTP_URL/api/dvr/entry/grid_upcoming") || return "$?"
   upcoming_text=$(entries_to_text "$upcoming")
 
   log "Upcoming: $upcoming_text"
@@ -156,7 +137,7 @@ get_finished() {
   curl_local_options="$curl_local_options --data sort=start_real"
   curl_local_options="$curl_local_options --data dir=DESC"
   curl_local_options="$curl_local_options --data limit=$limit"
-  finished=$(request $curl_local_options "$TVHEADEND_HTTP_URL/api/dvr/entry/grid_finished")
+  finished=$(request $curl_local_options "$TVHEADEND_HTTP_URL/api/dvr/entry/grid_finished") || return "$?"
   finished_text=$(entries_to_text "$finished")
 
   log "Finished: $finished_text"
@@ -165,27 +146,28 @@ get_finished() {
 
 
 ###############################################################################
-# Publish Tvheadend presets per MQTT
+# Publish and subscribe via MQTT
 ###############################################################################
 
-publish_status() {
-  publish get_status "$MQTT_TOPIC_PREFIX/status"
+publish() {
+  require_var MQTT_BROKER_HOSTNAME || return "$?"
+  require_command mosquitto_pub    || return "$?"
+  info="$1"
+  [ -z "$info" ] && log "Missing argument for requested Tvheadend info" && return "$rc_missing_arg"
+
+  command="get_$info"
+  if $(type -t "$command" | grep -q "^$command\( is a shell function\)\?\$"); then
+    message=$("$command")
+  else
+    message="Error: Unsupported Tvheadend info '$info'"
+  fi
+
+  log "Message: $message"
+  mosquitto_pub -h "$MQTT_BROKER_HOSTNAME" -t "$MQTT_TOPIC_PREFIX/$info" -m "$message"
 }
 
-publish_subscriptions() {
-  publish get_subscriptions "$MQTT_TOPIC_PREFIX/subscriptions"
-}
-
-publish_connections() {
-  publish get_connections "$MQTT_TOPIC_PREFIX/connections"
-}
-
-publish_upcoming() {
-  publish get_upcoming "$MQTT_TOPIC_PREFIX/upcoming"
-}
-
-publish_finished() {
-  publish get_finished "$MQTT_TOPIC_PREFIX/finished"
+subscribe() {
+  mosquitto_sub -h "$MQTT_BROKER_HOSTNAME" -t "$MQTT_TOPIC_PREFIX/request" | while read info; do publish "$info"; done
 }
 
 
@@ -193,7 +175,7 @@ publish_finished() {
 # Prepare environment
 ###############################################################################
 
-prepare_env
+prepare_env || exit "$?"
 
 
 ###############################################################################
